### ISSUE TITLE
fa-loading-icon is not getting visible over google maps?

### ISSUE THREAD

**Issue by devjangra031** [alemonteiro/jquery-fa-loading#1]
Hi,
I am trying to use this plugin for div loading in which google map is getting visible. The icon is coming in the debugger but it's not getting visible over the google maps. Any solutions for this?

**Comment by alemonteiro** [comment]
It's just a matter of z-index, use the above css and it will work.

.jq-fa-loading .fa-loading-modal { z-index: 10; }
.jq-fa-loading .fa-loading-content-wrapper  { z-index: 11; }

Check a demo: http://jsfiddle.net/alemonteiro/ttxefubj/3/
